-- 1) Conta base
CREATE TABLE T_CONTA (
    id_conta NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    senha VARCHAR2(35) NOT NULL,
    telefone VARCHAR2(25) NOT NULL,
    saldo NUMBER(15,2) NOT NULL,
    tipo_conta VARCHAR2(20) NOT NULL, -- 'PESSOAL' ou 'EMPRESARIAL'
    CONSTRAINT pk_conta PRIMARY KEY (id_conta),
    CONSTRAINT uq_email UNIQUE (email),
    CONSTRAINT ck_tipo_conta CHECK (tipo_conta IN ('PESSOAL','EMPRESARIAL'))
);

-- 2) Subtipo: pessoal
CREATE TABLE T_CONTA_PESSOAL (
    id_conta NUMBER NOT NULL,
    cpf VARCHAR2(11) NOT NULL,
    CONSTRAINT pk_conta_pessoal PRIMARY KEY (id_conta),
    CONSTRAINT fk_pessoal_conta FOREIGN KEY (id_conta) REFERENCES T_CONTA (id_conta),
    CONSTRAINT uq_cpf UNIQUE (cpf),
    CONSTRAINT ck_cpf_digits CHECK (REGEXP_LIKE(cpf, '^[0-9]{11}$')) 
);

-- 3) Subtipo: empresarial
CREATE TABLE T_CONTA_EMPRESARIAL (
    id_conta NUMBER NOT NULL,
    cnpj VARCHAR2(14) NOT NULL,
    CONSTRAINT pk_conta_empresarial PRIMARY KEY (id_conta),
    CONSTRAINT fk_empresarial_conta FOREIGN KEY (id_conta) REFERENCES T_CONTA (id_conta),
    CONSTRAINT uq_cnpj UNIQUE (cnpj),
    CONSTRAINT ck_cnpj_digits CHECK (REGEXP_LIKE(cnpj, '^[0-9]{14}$')) 
);

-- 4) Carteira
CREATE TABLE T_CARTEIRA (
    id_carteira NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_conta NUMBER NOT NULL,
    saldo NUMBER(15,2) NOT NULL,
    CONSTRAINT pk_carteira PRIMARY KEY (id_carteira),
    CONSTRAINT fk_carteira_conta FOREIGN KEY (id_conta) REFERENCES T_CONTA (id_conta)
);

-- 5) Ativo
CREATE TABLE T_ATIVO (
    id_ativo NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(50) NOT NULL,
    simbolo VARCHAR2(10) NOT NULL,              -- troquei para VARCHAR2
    cotacao NUMBER(15,2) NOT NULL,
    CONSTRAINT pk_ativo PRIMARY KEY (id_ativo),
    CONSTRAINT uq_ativo_simbolo UNIQUE (simbolo) -- ajuda muito nas consultas
);

-- 6) Tabela associativa carteira-ativo (N:N)
CREATE TABLE T_CARTEIRA_ATIVO (
    id_carteira NUMBER NOT NULL,
    id_ativo NUMBER NOT NULL,
    quantidade NUMBER(15,2) NOT NULL,
    preco_medio NUMBER(15,2) NOT NULL,
    data_primeira_compra DATE,
    data_ultimo_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_carteira_ativo PRIMARY KEY (id_carteira,id_ativo),
    CONSTRAINT fk_carteira_ativo_carteira FOREIGN KEY (id_carteira) REFERENCES T_CARTEIRA (id_carteira),
    CONSTRAINT fk_carteira_ativo_ativo FOREIGN KEY (id_ativo) REFERENCES T_ATIVO (id_ativo),
    CONSTRAINT ck_quantidade_positiva CHECK (quantidade > 0),
    CONSTRAINT ck_preco_medio_positivo CHECK (preco_medio > 0)
);

-- 7) Ordem
CREATE TABLE T_ORDEM (
    id_ordem NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_ativo NUMBER NOT NULL,
    id_carteira NUMBER NOT NULL,
    tipo VARCHAR2(6) NOT NULL,                   -- 'compra' ou 'venda'
    status VARCHAR2(20) NOT NULL,                -- 'executada', 'pendente', etc.
    data_lancamento TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    quantidade NUMBER(15,2) NOT NULL,
    preco NUMBER(15,2) NOT NULL,
    CONSTRAINT pk_ordem PRIMARY KEY (id_ordem),
    CONSTRAINT ck_tipo_ordem CHECK (tipo IN ('compra', 'venda')),
    CONSTRAINT ck_status_ordem CHECK (status IN ('executada', 'pendente')),
    CONSTRAINT fk_ordem_ativo FOREIGN KEY (id_ativo) REFERENCES T_ATIVO (id_ativo),
    CONSTRAINT fk_ordem_carteira FOREIGN KEY (id_carteira) REFERENCES T_CARTEIRA (id_carteira),
    CONSTRAINT ck_quantidade_ordem_positiva CHECK (quantidade > 0),
    CONSTRAINT ck_preco_ordem_positivo CHECK (preco > 0)
); 

-- 8) Transação (guarda executado); 'valor' como coluna virtual derivada
CREATE TABLE T_TRANSACAO (
    id_transacao NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_ordem_compra NUMBER NOT NULL,
    id_ordem_venda NUMBER NOT NULL,
    id_ativo NUMBER NOT NULL,
    quantidade NUMBER(15,2) NOT NULL,            -- executada
    preco NUMBER(15,2) NOT NULL,                 -- executado
    valor NUMBER(21,2) GENERATED ALWAYS AS (quantidade * preco) VIRTUAL,
    taxa NUMBER(10,6) NOT NULL,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_transacao PRIMARY KEY (id_transacao),
    CONSTRAINT fk_transacao_ativo FOREIGN KEY (id_ativo) REFERENCES T_ATIVO(id_ativo),
    CONSTRAINT fk_transacao_ordem_compra FOREIGN KEY (id_ordem_compra) REFERENCES T_ORDEM(id_ordem),
    CONSTRAINT fk_transacao_ordem_venda FOREIGN KEY (id_ordem_venda) REFERENCES T_ORDEM(id_ordem),
    CONSTRAINT ck_quantidade_transacao_positiva CHECK (quantidade > 0),
    CONSTRAINT ck_preco_transacao_positivo CHECK (preco > 0)
);



-- Cascata na exclusão (assim você pode apagar T_CONTA e o subtipo vai junto)
ALTER TABLE T_CONTA_PESSOAL DROP CONSTRAINT fk_pessoal_conta;
ALTER TABLE T_CONTA_PESSOAL
  ADD CONSTRAINT fk_pessoal_conta
  FOREIGN KEY (id_conta) REFERENCES T_CONTA (id_conta) ON DELETE CASCADE;

ALTER TABLE T_CONTA_EMPRESARIAL DROP CONSTRAINT fk_empresarial_conta;
ALTER TABLE T_CONTA_EMPRESARIAL
  ADD CONSTRAINT fk_empresarial_conta
  FOREIGN KEY (id_conta) REFERENCES T_CONTA (id_conta) ON DELETE CASCADE;

ALTER TABLE T_CARTEIRA_ATIVO DROP CONSTRAINT fk_carteira_ativo_ativo;
ALTER TABLE T_CARTEIRA_ATIVO
  ADD CONSTRAINT fk_carteira_ativo_ativo
  FOREIGN KEY (id_ativo) REFERENCES T_ATIVO (id_ativo) ON DELETE CASCADE;


ALTER TABLE T_CARTEIRA DROP CONSTRAINT fk_carteira_conta;
  ALTER TABLE T_CARTEIRA
  ADD CONSTRAINT fk_carteira_conta
  FOREIGN KEY (id_conta) REFERENCES T_CONTA (id_conta) ON DELETE CASCADE;


ALTER TABLE T_CARTEIRA_ATIVO DROP CONSTRAINT fk_carteira_ativo_carteira;
  ALTER TABLE T_CARTEIRA_ATIVO
  ADD CONSTRAINT fk_carteira_ativo_carteira
  FOREIGN KEY (id_carteira) REFERENCES T_CARTEIRA (id_carteira) ON DELETE CASCADE;

ALTER TABLE T_ORDEM DROP CONSTRAINT fk_ordem_ativo;
ALTER TABLE T_ORDEM 
  ADD CONSTRAINT fk_ordem_ativo
  FOREIGN KEY (id_ativo) REFERENCES T_ATIVO (id_ativo) ON DELETE CASCADE;

ALTER TABLE T_ORDEM DROP CONSTRAINT fk_ordem_carteira;
ALTER TABLE T_ORDEM 
  ADD CONSTRAINT fk_ordem_carteira
  FOREIGN KEY (id_carteira) REFERENCES T_CARTEIRA (id_carteira) ON DELETE CASCADE;

ALTER TABLE T_TRANSACAO DROP CONSTRAINT fk_transacao_ativo;
ALTER TABLE T_TRANSACAO
  ADD CONSTRAINT fk_transacao_ativo
  FOREIGN KEY (id_ativo) REFERENCES T_ATIVO(id_ativo) ON DELETE CASCADE;

ALTER TABLE T_TRANSACAO DROP CONSTRAINT fk_transacao_ordem_venda;
ALTER TABLE T_TRANSACAO
  ADD CONSTRAINT fk_transacao_ordem_venda
  FOREIGN KEY (id_ordem_venda) REFERENCES T_ORDEM(id_ordem) ON DELETE CASCADE;

ALTER TABLE T_TRANSACAO DROP CONSTRAINT fk_transacao_ordem_compra;
ALTER TABLE T_TRANSACAO
  ADD CONSTRAINT fk_transacao_ordem_compra
  FOREIGN KEY (id_ordem_compra) REFERENCES T_ORDEM(id_ordem) ON DELETE CASCADE;
